SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.USER_ACCOUNT', 'PASSWORD_HASH') IS NULL
BEGIN
    ALTER TABLE dbo.USER_ACCOUNT
        ADD PASSWORD_HASH nvarchar(500) NULL;
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.USER_ACCOUNT')
      AND name = 'UX_USER_ACCOUNT_ACCOUNT'
)
BEGIN
    CREATE UNIQUE INDEX UX_USER_ACCOUNT_ACCOUNT
        ON dbo.USER_ACCOUNT (USER_ACCOUNT)
        WHERE USER_ACCOUNT IS NOT NULL;
END;

COMMIT TRANSACTION;
