SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

ALTER TABLE dbo.USER_ACCOUNT
    ALTER COLUMN INSERT_OP varchar(50) NULL;
ALTER TABLE dbo.USER_ACCOUNT
    ALTER COLUMN UPDATE_OP varchar(50) NULL;

ALTER TABLE dbo.QUESTIONS_RECORDS
    ALTER COLUMN INSERT_OP varchar(50) NULL;
ALTER TABLE dbo.QUESTIONS_RECORDS
    ALTER COLUMN UPDATE_OP varchar(50) NULL;

ALTER TABLE dbo.ANSWERS_RECORDS
    ALTER COLUMN INSERT_OP varchar(50) NULL;
ALTER TABLE dbo.ANSWERS_RECORDS
    ALTER COLUMN UPDATE_OP varchar(50) NULL;

ALTER TABLE dbo.CONVERSATION_RECORDS
    ALTER COLUMN INSERT_OP varchar(50) NULL;
ALTER TABLE dbo.CONVERSATION_RECORDS
    ALTER COLUMN UPDATE_OP varchar(50) NULL;

COMMIT TRANSACTION;
