SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

UPDATE c
SET c.CHAT_TITLE = LEFT(q.QUESTION_TEXT, 255),
    c.UPDATE_DT = SYSUTCDATETIME(),
    c.UPDATE_OP = COALESCE(u.USER_ACCOUNT, 'NAA_API')
FROM dbo.CONVERSATION_RECORDS AS c
INNER JOIN dbo.QUESTIONS_RECORDS AS q
    ON q.UNIQUE_ID = c.QUESTION_ID
LEFT JOIN dbo.USER_ACCOUNT AS u
    ON u.UNIQUE_ID = c.USER_ID
WHERE q.QUESTION_TEXT IS NOT NULL
  AND
  (
      c.CHAT_TITLE IS NULL
      OR c.CHAT_TITLE <> LEFT(q.QUESTION_TEXT, 255)
  );

COMMIT TRANSACTION;
