SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.CONVERSATION_RECORDS', 'CONVERSATION_ID') IS NULL
BEGIN
    IF COL_LENGTH('dbo.CONVERSATION_RECORDS', 'THREAD_ID') IS NOT NULL
    BEGIN
        EXEC sys.sp_rename
            N'dbo.CONVERSATION_RECORDS.THREAD_ID',
            N'CONVERSATION_ID',
            'COLUMN';
    END
    ELSE
    BEGIN
        EXEC
        (
            'ALTER TABLE dbo.CONVERSATION_RECORDS ADD CONVERSATION_ID varchar(36) NULL;
             UPDATE dbo.CONVERSATION_RECORDS SET CONVERSATION_ID = UNIQUE_ID WHERE CONVERSATION_ID IS NULL;
             ALTER TABLE dbo.CONVERSATION_RECORDS ALTER COLUMN CONVERSATION_ID varchar(36) NOT NULL;
             ALTER TABLE dbo.CONVERSATION_RECORDS ADD CONSTRAINT DF_CONVERSATION_RECORDS_CONVERSATION_ID
                 DEFAULT (CONVERT(varchar(36), NEWID())) FOR CONVERSATION_ID;'
        );
    END
END;
GO

IF OBJECT_ID('dbo.DF_CONVERSATION_RECORDS_THREAD_ID', 'D') IS NOT NULL
BEGIN
    EXEC sys.sp_rename
        N'dbo.DF_CONVERSATION_RECORDS_THREAD_ID',
        N'DF_CONVERSATION_RECORDS_CONVERSATION_ID',
        'OBJECT';
END;

IF EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.CONVERSATION_RECORDS')
      AND name = 'IX_CONVERSATION_RECORDS_THREAD_ID'
)
BEGIN
    EXEC sys.sp_rename
        N'dbo.CONVERSATION_RECORDS.IX_CONVERSATION_RECORDS_THREAD_ID',
        N'IX_CONVERSATION_RECORDS_CONVERSATION_ID',
        'INDEX';
END;

IF COL_LENGTH('dbo.CONVERSATION_RECORDS', 'IS_DELETED') IS NULL
BEGIN
    ALTER TABLE dbo.CONVERSATION_RECORDS
        ADD IS_DELETED bit NOT NULL
            CONSTRAINT DF_CONVERSATION_RECORDS_IS_DELETED DEFAULT (0);
END;

IF COL_LENGTH('dbo.CONVERSATION_RECORDS', 'DELETED_AT') IS NULL
BEGIN
    ALTER TABLE dbo.CONVERSATION_RECORDS
        ADD DELETED_AT datetime2(3) NULL;
END;

IF COL_LENGTH('dbo.CONVERSATION_RECORDS', 'DELETED_BY') IS NULL
BEGIN
    ALTER TABLE dbo.CONVERSATION_RECORDS
        ADD DELETED_BY varchar(50) NULL;
END;

IF COL_LENGTH('dbo.CONVERSATION_RECORDS', 'AGENT_THREAD_ID') IS NULL
BEGIN
    ALTER TABLE dbo.CONVERSATION_RECORDS
        ADD AGENT_THREAD_ID nvarchar(128) NULL;
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.CONVERSATION_RECORDS')
      AND name = 'IX_CONVERSATION_RECORDS_CONVERSATION_ID'
)
BEGIN
    CREATE INDEX IX_CONVERSATION_RECORDS_CONVERSATION_ID
        ON dbo.CONVERSATION_RECORDS (CONVERSATION_ID, IS_DELETED, INSERT_DT);
END;

COMMIT TRANSACTION;
